// USER REDUCER
export const GET_ALL_USER = "GET_ALL_USER";
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

// PRODUUCT REDUCER
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

// MENU reducer
export const LOAD_MENU = "LOAD_MENU";
export const UPDATE_MENU = "UPDATE_MENU";
export const REMOVE_MENU = "REMOVE_MENU";

// COMMON: SUPPORTER, HEADER, FOOTER....
export const LOAD_SUPPORTER = "LOAD_SUPPORTER";
export const SET_PRODUCT_FILTER = "SET_PRODUCT_FILTER";
